"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import datetime
import dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_file = os.path.join(BASE_DIR, ".env")
if os.path.isfile(dotenv_file):
    dotenv.load_dotenv(dotenv_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xn3w=6bb)wk$-^*6u$_oww4+e3yniy7a#c$gmz-6)cvf)z($m5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before django.contrib.admin
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    
    # 3rd party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'fcm_django',
    
    # Custom apps
    'accounts',
    'exchange',
    'intel',
    'network',
    'notification',
    'donation',
    'blog',
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'uuid',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': datetime.timedelta(minutes=120),
    'SLIDING_TOKEN_REFRESH_LIFETIME': datetime.timedelta(days=365),
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

BASE_STATIC_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = 'static/'
STATICFILES_DIR = (
        BASE_DIR / 'static'
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Added by me
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_PORT = 587
EMAIL_USE_TLS = True

DEV_FORMAT = ""
COMMON_FORMAT = (
    "%(levelname)s %(asctime)s %(module)s %(process)d %(pathname)s %(funcName)s %(message)s"
)

# FCM Django settings
FCM_DJANGO_SETTINGS = {
    # default: None - set either this, or absolute path to service key file, or app instance variable
    "FCM_SERVER_KEY": None,
    # absolute path to service key file
    "FCM_SERVICE_ACCOUNT_KEY_PATH": os.path.join(BASE_DIR, "notification/firebase_account_file/operation-vanguard-78d91-firebase-adminsdk-fbsvc-750f7c4c70.json"),
    # default: None - specify the user model that does a OneToOneField to FCMDevice
    "ONE_DEVICE_PER_USER": True,
    # default: False - if True, delete FCMDevice if token is invalid
    "DELETE_INACTIVE_DEVICES": True,
    # default: True - update registration tokens
    "UPDATE_ON_DUPLICATE_REG_ID": True,
    # default: False - use APNs token for sending messages to iOS
    "USE_SANDBOX": DEBUG,
    # default: False - send multicast messages in chunks
    "FCM_MAX_RECIPIENTS": 1000,
    # default: 5 - number of retries for failed requests
    "FCM_ERROR_RETRY_COUNT": 3,
    # default: False - True=iOS & Android, False=only Android
    "FCM_SEND_TO_ALL_DEVICES": True,
    # Model to use for FCMDevice - defaults to fcm_django.models.FCMDevice
    "FCM_DEVICE_MODEL": "notification.FCMDeviceCustom",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "dev": {"format": DEV_FORMAT},
        "common": {"format": COMMON_FORMAT},
    },
    "handlers": {
        "file_debug": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/debug.log"),
            "formatter": "common",
        },
        "file_info": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/info.log"),
            "formatter": "common",
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/error.log"),
            "formatter": "common",
        },
        "file_warning": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/warning.log"),
            "formatter": "common",
        },
    },
    "loggers": {
        "": {
            "handlers": ["file_debug", "file_info", "file_error", "file_warning"],
            "level": "DEBUG",
        }
    }
}

# ==============================================================================
# JAZZMIN SETTINGS
# ==============================================================================

JAZZMIN_SETTINGS = {
    # Title on the login screen & main admin dashboard
    "site_title": "Vanguard Admin",
    "site_header": "Vanguard",
    "site_brand": "Vanguard Veterans Platform",
    
    # Logo to use for your site (must be present in static files)
    # "site_logo": "images/vanguard-logo.png",  # Uncomment when logo is added
    
    # Logo to use for your site on smaller screens
    # "site_logo_classes": "img-circle",
    
    # Relative path to a favicon
    # "site_icon": "images/favicon.ico",  # Uncomment when favicon is added
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to Vanguard Admin Portal",
    
    # Copyright on the footer
    "copyright": "Vanguard Veterans Platform",
    
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    
    # Whether to show the search bar
    "search_model": ["accounts.User"],
    
    # Field name on user model that contains avatar
    "user_avatar": None,
    
    ############
    # Top Menu #
    ############
    
    # Links to put along the top menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # {"name": "📊 Dashboard", "url": "admin_dashboard", "permissions": ["auth.view_user"]},
        {"model": "accounts.User"},
        {"app": "intel"},
    ],
    
    #############
    # Side Menu #
    #############
    
    # Whether to display the side menu
    "show_sidebar": True,
    
    # Whether to aut expand the menu
    "navigation_expanded": True,
    
    # Hide these apps when generating side menu
    "hide_apps": ["auth"],
    
    # Hide these models when generating side menu
    "hide_models": [],
    
    # Custom menu ordering (will override alphabetical)
    "order_with_respect_to": [
        "accounts",
        "intel", 
        "exchange",
        "donation",
        "blog",
        "network",
        "notification",
        "auth",
    ],
    
    # Custom icons for models (Font Awesome 5)
    "icons": {
        # Django Auth
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Accounts App
        "accounts": "fas fa-user-circle",
        "accounts.User": "fas fa-user-shield",
        "accounts.UserProfile": "fas fa-id-card",
        "accounts.UserRole": "fas fa-user-tag",
        "accounts.UserOTP": "fas fa-key",
        "accounts.MediaStorage": "fas fa-images",
        
        # Intel Management App
        "intel": "fas fa-brain",
        "intel.Intel": "fas fa-lightbulb",
        "intel.IntelMedia": "fas fa-photo-video",
        "intel.IntelCategory": "fas fa-folder-open",
        "intel.IntelComment": "fas fa-comments",
        "intel.IntelLike": "fas fa-heart",
        "intel.CommentLike": "fas fa-thumbs-up",
        
        # Exchange App
        "exchange": "fas fa-handshake",
        "exchange.Exchange": "fas fa-store",
        "exchange.ExchangeVerification": "fas fa-certificate",
        "exchange.Category": "fas fa-tags",
        "exchange.SubCategory": "fas fa-tag",
        
        # Network App
        "network": "fas fa-project-diagram",
        "network.Follow": "fas fa-user-friends",
        
        # Notification App
        "notification": "fas fa-bell",
        "notification.Notification": "fas fa-bell",
        "notification.FCMDeviceCustom": "fas fa-mobile-alt",
        "notification.NotificationTemplate": "fas fa-file-alt",
        "notification.NotificationLog": "fas fa-history",
        
        # Donation App
        "donation": "fas fa-hand-holding-usd",
        "donation.Donation": "fas fa-donate",
        "donation.DonationTarget": "fas fa-bullseye",
        
        # Blog App
        "blog": "fas fa-blog",
        "blog.Blog": "fas fa-newspaper",
    },
    
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    #############
    # UI Tweaks #
    #############
    
    # Relative paths to custom CSS/JS scripts
    "custom_css": None,
    "custom_js": None,
    
    # Whether to show the quick-add button
    "show_quick_add": True,
    
    # Whether to link font from fonts.googleapis.com
    "use_google_fonts_cdn": True,
    
    # Whether to show the language chooser
    "show_language_chooser": False,
    
    ###############
    # Change view #
    ###############
    
    # Render out the change view as a single form, or in tabs
    "changeform_format": "horizontal_tabs",
    
    # Override change forms per model
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-primary",
    "navbar": "navbar-navy navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
